ログ追加

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,8 +25,11 @@ jobs:
       
       - name: Debug .output
         run: |
-          echo "===== .output contents ====="
-          ls -R .output || echo ".output not found"
+          echo "=== CHECK .output ==="
+          pwd
+          ls -al .
+          ls -al .output || echo ".output not found"
+          ls -R .output || echo ".output empty"
 
       - name: Upload files to VPS
         uses: appleboy/scp-action@v0.1.4
